#!/bin/ash
PUID=${PUID:-1000}
PGID=${PGID:-1000}

mkdir -p /config/db
mkdir -p /config/artwork
mkdir -p /series
mkdir -p /movies
mkdir -p /transcode

if id -u $PUID > /dev/null 2>&1 && id -g $PGID > /dev/null 2>&1; then
    chown $PUID:$PGID /config
    chown $PUID:$PGID /movies
    chown $PUID:$PGID /series
    chown $PUID:$PGID /transcode
    su -m $PUID -c './src/main'  # Run the Go application as the specified user
else
    ./src/main  # Run the Go application
fi

touch /config/restart.txt
touch /config/shutdown.txt

last_restart_modified=$(stat -c %Y /config/restart.txt)
last_shutdown_modified=$(stat -c %Y /config/shutdown.txt)

while true; do
    APP_PORT=8080  # Set the port for the Go application

    if id -u $PUID > /dev/null 2>&1 && id -g $PGID > /dev/null 2>&1; then
        su -m $PUID -c './src/main --port '"$APP_PORT" &
    else
        ./src/main --port $APP_PORT &
    fi

    app_pid=$!

    while true; do
        sleep 1
        new_restart_modified=$(stat -c %Y /config/restart.txt)
        new_shutdown_modified=$(stat -c %Y /config/shutdown.txt)
        if [ "$new_restart_modified" != "$last_restart_modified" ]; then
            last_restart_modified=$new_restart_modified
            kill $app_pid
            wait $app_pid
            break
        elif [ "$new_shutdown_modified" != "$last_shutdown_modified" ]; then
            kill $app_pid
            wait $app_pid
            exit 0
        fi
    done
done