name: Build Image

on:
  push:
    branches:
      - main
      - develop*
  pull_request:
    types: [closed]
    branches:
      - main
      - develop*

env:
  IMAGE_NAME: ${{ github.repository }}
  BUILDX_CACHE_DIR: /tmp/.buildx-cache

jobs:
  push_to_registries:
    name: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DockerUsername }}
          password: ${{ secrets.DockerToken }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables based on branch
        id: set_tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
            echo "version=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
            echo "BRANCH_NAME=latest" >> $GITHUB_ENV
          else
            BRANCH_NAME=$(echo "${{ github.ref }}" | sed -r 's/refs\/heads\///g')
            echo "tag=develop" >> $GITHUB_OUTPUT
            echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          fi

      - name: Convert IMAGE_NAME to lowercase
        run: echo "IMAGE_NAME=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ env.BUILDX_CACHE_DIR }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push multi-arch images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: true
          attests: |
            sbom
            provenance=mode=max
          sbom: true
          cache-from: type=local,src=${{ env.BUILDX_CACHE_DIR }}
          cache-to: type=local,dest=${{ env.BUILDX_CACHE_DIR }}-new,mode=max
          tags: |
            docker.io/${{ env.IMAGE_NAME }}:${{ steps.set_tag.outputs.tag }}
            docker.io/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.set_tag.outputs.tag }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}

      - name: Move cache
        run: |
          rm -rf ${{ env.BUILDX_CACHE_DIR }}
          mv ${{ env.BUILDX_CACHE_DIR }}-new ${{ env.BUILDX_CACHE_DIR }}
