name: Build and Push Docker Image

on:
  push:
    branches: [main, develop*]
  pull_request:
    types: [closed]
    branches: [main, develop*]

env:
  REGISTRY_DOCKER: docker.io
  REGISTRY_GHCR: ghcr.io
  CACHE_PATH: /tmp/.buildx-cache
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registries
        uses: docker/login-action@v3
        with:
          registry: ${{ matrix.registry }}
          username: ${{ matrix.registry == 'ghcr.io' && github.actor || secrets.DockerUsername }}
          password: ${{ matrix.registry == 'ghcr.io' && secrets.GITHUB_TOKEN || secrets.DockerToken }}
        strategy:
          matrix:
            registry: [docker.io, ghcr.io]

      - name: Prepare tags
        id: prep
        run: |
          IMAGE_NAME=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG=$([ "$BRANCH" = "main" ] && echo "latest" || echo "develop")

          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: true
          sbom: true
          cache-from: type=local,src=${{ env.CACHE_PATH }}
          cache-to: type=local,dest=${{ env.CACHE_PATH }},mode=max
          tags: |
            ${{ env.REGISTRY_DOCKER }}/${{ steps.prep.outputs.image_name }}:${{ steps.prep.outputs.tag }}
            ${{ env.REGISTRY_DOCKER }}/${{ steps.prep.outputs.image_name }}:${{ steps.prep.outputs.branch }}
            ${{ env.REGISTRY_GHCR }}/${{ steps.prep.outputs.image_name }}:${{ steps.prep.outputs.tag }}
            ${{ env.REGISTRY_GHCR }}/${{ steps.prep.outputs.image_name }}:${{ steps.prep.outputs.branch }}
