name: Test Frontend

on: 
    push:
        branches:
            - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies and test
        working-directory: frontend
        run: |
            npm ci
            npm run test -- --passWithNoTests